# Generated by Django 4.2.19 on 2025-02-21 08:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Chat', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='image',
            field=models.TextField(blank=True, null=True),
        ),
    ]
